insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Relapsing fever NOS', 1, 1);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Hem early preg-delivered', 2, 2);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Acc poison-methadone', 3, 3);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Lymphomas NEC inguin', 4, 4);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Antineoplastic chemo enc', 5, 5);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('TB of bone NEC-oth test', 6, 6);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('TB pleurisy-no exam', 7, 7);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Bact arthritis-forearm', 8, 8);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Vaginal hematoma', 9, 9);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Esophag varices w bleed', 10, 10);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Late sympt syphilis NOS', 11, 11);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Adv eff antilipemics', 12, 12);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Sqam cell ca sclp/skn nk', 13, 13);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Monofixation syndrome', 14, 14);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Appendix injury-closed', 15, 15);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Late eff inj periph vess', 16, 16);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Mv coll w ped-anim rid', 17, 17);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Blood asp w resp sympt', 18, 18);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Fracture of pubis-open', 19, 19);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('NB cutaneous hemorrhage', 20, 20);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Preg w poor obs hx NEC', 21, 21);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Tobacco use disord-unsp', 22, 22);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Ben neo nasal cav/sinus', 23, 23);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Norml pressure hydroceph', 24, 24);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Cleft lip NOS', 25, 25);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Renal dis NOS-antepartum', 26, 26);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Lactation fail-unspec', 27, 27);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Opn skl base fx-coma NOS', 28, 28);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Ocl art NOS wo infrct', 29, 29);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Complic labor NEC-deliv', 30, 30);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Dis mineral metabol NEC', 31, 31);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Kaschin-beck dis NEC', 32, 32);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Pulmon TB NOS-cult dx', 33, 33);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Ankylosis-hand', 34, 34);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Pathol dislocat-pelvis', 35, 35);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Ocl vrtb art w infrct', 36, 36);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Atrophy mandible-severe', 37, 37);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Malignant neo anus NOS', 38, 38);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Disloc midtarsal-open', 39, 39);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Pseudopterygium', 40, 40);
insert into comentario (Texto, Id_Usuario, Id_Objeto) values ('Carbuncle of foot', 41, 41);
